name: "Gollum Page Watcher"
author: "benmatselby"
description: "📦 A GitHub Action to watch for GitHub Wiki Page changes, and then notify a Slack channel"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "book-open"
  color: "purple"
inputs:
  slack_webhook:
    description: "The Slack Webhook URL required to post a message to your workspace."
    required: true
  slack_username:
    description: "The Slack username if you want to define it, otherwise it will be what you have defined in Slack."
    required: false
  slack_channel:
    description: "The Slack channel if you want to define it, otherwise it will be what you have defined in Slack."
    required: false
  pages_to_watch:
    description: "A regex of page titles you want to watch, in order to get a notification. If not defined, all pages are watched."
    required: false
