name: "Gollum Page Watcher"
author: "benmatselby"
description: "📦 A GitHub Action to watch for certain pages to change in the wiki, and then notify in a Slack channel"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "book-open"
  color: "purple"
inputs:
  watch_pages:
    description: "The pages we should be watching for changes to. A comma separated list of string expressions."
    required: true
  slack_webhook:
    description: "The Slack Webhook URL required to post a message to your workspace."
    required: true
  slack_username:
    description: "The Slack username if you want to define it, otherwise it will be what you have defined in Slack."
    required: false
  slack_channel:
    description: "The Slack channel if you want to define it, otherwise it will be what you have defined in Slack."
    required: false
