name: Go
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: "go.mod"
          cache: true
        id: go

      - name: Get dependencies
        run: |
          make install

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: latest
          args: --verbose

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test
